try:
    # want to attempt this code
    # may have an error
    result = 10 + "87"  #we created here an error
    print(result)
except:
    print("hey it looks like you arent adding correctly!") # the rest of block code was still able to execute with the
                                                           # except statement, my whole program wasnt shut down iz za errora



